[versions]
androidGradlePlugin = "9.0.0"
kotlin = "2.2.0"
dokka = "2.2.0-Beta"

[libraries]
android-gradlePlugin-api = { group = "com.android.tools.build", name = "gradle-api", version.ref = "androidGradlePlugin" }
android-gradlePlugin-impl = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
dokka-gradlePlugin = { group = "org.jetbrains.dokka", name = "dokka-gradle-plugin", version.ref = "dokka" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
